### ISSUE TITLE
parallel calls to C3D_SyncDisplayTransfer and gspWaitForVBlank cause lockup

### ISSUE THREAD

**Issue by badda71** [fincs/citro3d#48]
I have the following issue: My homebrew consists of two threads, one thread drawing textures to the screen inbetween calls to gspWaitForVBlank, the other thread setting up the textures. Now, I'm facing the issue that I have random lockups and the backtraces from gdb always look like this:

**Thread 1 (drawing thread):**
```
Thread 7 (Thread 266):
#0  svcArbitrateAddress ()
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/svc.s:250
#1  0x002a993c in LightEvent_Wait (event=0x173458c <gspEvents+16>,
    event@entry=0x17213a4 <runThread>)
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/synchronization.c:206
#2  0x002aed88 in gspWaitForEvent (id=id@entry=GSPGPU_EVENT_VBlank0,
    nextEvent=nextEvent@entry=true)
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/services/gspgpu.c:86
#3  0x002604c0 in videoThread (data=<optimized out>)
    at src/video/n3ds/SDL_n3dsvideo.c:549
[...]
```

**Thread 2 (texture setup & main thread):**
```
Thread 1 (Thread 243):
#0  svcArbitrateAddress ()
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/svc.s:250
#1  0x002aede8 in gspWaitForAnyEvent ()
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/services/gspgpu.c:106
#2  0x002a602c in C3Di_WaitAndClearQueue (timeout=<optimized out>)
    at /home/fincs/pacman-packages/citro3d/src/source/renderqueue.c:132
#3  0x002a66d4 in C3Di_SafeDisplayTransfer (flags=3, outdim=33554944,
    outadr=0x30a2ba00, indim=33554944, inadr=0x3092ba00)
    at /home/fincs/pacman-packages/citro3d/src/source/renderqueue.c:442
#4  C3D_SyncDisplayTransfer (inadr=0x3092ba00, indim=33554944,
    outadr=0x30a2ba00, outdim=33554944, flags=3)
    at /home/fincs/pacman-packages/citro3d/src/source/renderqueue.c:442
#5  0x0025f6e8 in drawBuffers (this=<optimized out>)
    at src/video/n3ds/SDL_n3dsvideo.c:566
[...]
```
Is this a C3D-bug? Or am I doing something wrong?

**Comment by fincs** [comment]
I'm sorry, but citro3d is not a multithread-capable API. It has neither been designed for or tested under a multithreaded scenario. You are supposed to keep all citro3d API calls within a single thread.

**Comment by badda71** [comment]
ok *sigh*. Guess I need to rewrite some code ...
